version: "2"
services:
  gateway:
    container_name: gateway
    image: gateway:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger,api-docs,gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=120
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - jhipster-registry
      - keycloak
      - microservice
  microservice:
    container_name: microservice
    image: skillshapes/microservice:latest
    environment:
      - _JAVA_OPTIONS=-Xmx1g -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger,api-docs,gateway"
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config/master
      - DATASOURCE_URL=jdbc:mariadb://microservice-mariadb:3306/skillshapes
      - SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_LOGOUT_URL=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/logout
      - JHIPSTER_SLEEP=120
    expose:
      - "8081"
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - microservice-mariadb
      - jhipster-registry
      - keycloak
  microservice-mariadb:
    container_name: microservice-db
    extends:
      file: microservice/src/main/docker/mariadb.yml
      service: skillshapes-mariadb
  jhipster-registry:
    container_name: jhipster-registry
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  keycloak:
    container_name: keycloak
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    extends:
      file: keycloak.yml
      service: keycloak

  #phpmyadmin:
  #  container_name: microservice-phpmyadmin
  #  image: phpmyadmin/phpmyadmin
  #  environment:
  #    - PMA_HOST=microservice-mariadb
  #    - PMA_USER=root
  #  ports:
  #    - 9090:80
  #  depends_on:
  #    - microservice-mariadb

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.1
    volumes:
      - source: ./elk/logstash/pipeline/gelf.conf
        target: /usr/share/logstash/pipeline/gelf.conf
        type: bind
    ports:
      - "12201:12201/udp"
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  jaegertracing:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - ES_TAGS_AS_FIELDS_ALL=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "16686:16686"
      - "5778:5778"
      - "14268:14268"

configs:
  logstash_pipeline:
    file: ./elk/logstash/pipeline/logstash.conf

networks:
  default:
    external:
      name: skillshapes-network
