version: "3.3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.1
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - "5601:5601"
    deploy:
      mode: replicated
      replicas: 1

configs:
  logstash_pipeline:
    file: ./elk/logstash/pipeline/logstash.conf
