version: "2"
services:
  gateway:
    container_name: gateway
    image: gateway:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - jhipster-registry
      - keycloak
  microservice-mariadb:
    container_name: microservice-db
    extends:
      file: microservice/src/main/docker/mariadb.yml
      service: skillshapes-mariadb
  jhipster-registry:
    container_name: jhipster-registry
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  keycloak:
    container_name: keycloak
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    extends:
      file: keycloak.yml
      service: keycloak
