version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    privileged: true
    user: root
    ports:
      - 18080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - ./jenkins/fingerprints:/var/jenkins_home/fingerprints
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  sonar:
    container_name: sonarqube
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    extends:
      file: microservice/src/main/docker/sonar.yml
      service: sonar
