#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTdhNjdhY2Y0MmNiMGQ3NWM4OWNjMTdlYThhZjhiMWQxOGVjYjI2MDk4MmY5MGY1NThlZDc5MjQxZjlkYzFlODNjYWIzODI0NTc0MTMzYmNkNzZmMDI2Yjk1ZDhkOWQ0MTY0Yg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@jhipster-registry:8761/eureka/

# Quarkus application
quarkus:
  jaeger:
    endpoint: http://jaeger:14268/api/traces
    hibernate-search-orm:
      elasticsearch:
        hosts: elasticsearch:9200
  oidc:
    auth-server-url: http://keycloak:9080/auth/realms/jhipster/
