jhipster:
  metrics:
    logs: # do report metrics in the logs for gateway applications
      enabled: false
logging:
  logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
    enabled: true
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://keycloak:9080/auth/realms/jhipster
eureka:
  instance:
    appname: gateway
